dtst_controller:
    path: /dtst
    defaults: { _controller: phpbbstudio.dtst.controller:handle }

dtst_manager:
    path: /dtst/manage
    defaults: { _controller: phpbbstudio.dtst.controller:manage }

dtst_cancel:
    path: /dtst/cancel
    defaults: { _controller: phpbbstudio.dtst.controller:cancel }
