imports:
    - { resource: parameters.yml }

services:
    phpbbstudio.dtst.listener:
        class: phpbbstudio\dtst\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@phpbbstudio.dtst.dtst_event_cron'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '@controller.helper'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.profile_listener:
        class: phpbbstudio\dtst\event\profile_listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@controller.helper'
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbstudio.dtst.tables.dtst_ranks%'
            - '%phpbbstudio.dtst.tables.dtst_reputation%'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.ucp_listener:
        class: phpbbstudio\dtst\event\ucp_listener
        arguments:
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@phpbbstudio.dtst.dtst_utils'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.acp_listener:
        class: phpbbstudio\dtst\event\acp_listener
        arguments:
            - '@request'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.dtst_utils:
        class: phpbbstudio\dtst\core\operator
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '%phpbbstudio.dtst.tables.dtst_privmsg%'
            - '%phpbbstudio.dtst.tables.dtst_ranks%'

    phpbbstudio.dtst.dtst_rep:
        class: phpbbstudio\dtst\core\reputation_functions
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@notification_manager'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%phpbbstudio.dtst.tables.dtst_reputation%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'

    phpbbstudio.dtst.dtst_event_cron:
        class: phpbbstudio\dtst\core\event_cron
        arguments:
            - '@config'
            - '@log'
            - '@phpbbstudio.dtst.dtst_rep'

    phpbbstudio.dtst.event.controller:
        class: phpbbstudio\dtst\controller\event_controller
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@notification_manager'
            - '@path_helper'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%phpbbstudio.dtst.tables.dtst_reputation%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '%phpbbstudio.dtst.tables.dtst_privmsg%'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbstudio.dtst.reputation.controller:
        class: phpbbstudio\dtst\controller\reputation_controller
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbstudio.dtst.dtst_rep'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%phpbbstudio.dtst.tables.dtst_reputation%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbstudio.dtst.mcp.controller:
        class: phpbbstudio\dtst\controller\mcp_controller
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@phpbbstudio.dtst.dtst_rep'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%phpbbstudio.dtst.tables.dtst_reputation%'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbstudio.dtst.notification.type.opting:
        class: phpbbstudio\dtst\notification\type\opting
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }

    phpbbstudio.dtst.notification.type.reputation:
        class: phpbbstudio\dtst\notification\type\reputation
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_slots_table, ['%phpbbstudio.dtst.tables.dtst_slots%']]
        tags:
            - { name: notification.type }
