imports:
    - { resource: parameters.yml }

services:
    phpbbstudio.dtst.listener:
        class: phpbbstudio\dtst\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '@controller.helper'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.ucp_listener:
        class: phpbbstudio\dtst\event\ucp_listener
        arguments:
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@phpbbstudio.dtst.dtst_utils'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.acp_listener:
        class: phpbbstudio\dtst\event\acp_listener
        arguments:
            - '@request'
        tags:
            - { name: event.listener }

    phpbbstudio.dtst.dtst_utils:
        class: phpbbstudio\dtst\core\operator
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '%phpbbstudio.dtst.tables.dtst_privmsg%'

    phpbbstudio.dtst.controller:
        class: phpbbstudio\dtst\controller\controller
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@notification_manager'
            - '@path_helper'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbstudio.dtst.dtst_utils'
            - '%phpbbstudio.dtst.tables.dtst_slots%'
            - '%phpbbstudio.dtst.tables.dtst_privmsg%'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbbstudio.dtst.notification.type.opting:
        class: phpbbstudio\dtst\notification\type\opting
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }
